Whisper models
JSchmie/ScrAIbe pull request #83
Opened 2024-05-13 09:58 UTC by mahenning

Added the whisperx model to the Transcriber class.

Made the choice that `Transcriber` is not an ABC class, because now one can use `Transcriber.load_model(..., whisper_type, ...)` to automatically load the right whisper/whisperx model.  
Tested with ScrAIbe-WebUI docker container and a transcript of a few mp3/mp4.

To load the appropiate model type, add e.g.
> models:
>    whisper_type: whisperx
to the config.yaml. Default is whisper.

2024-05-15 14:09 UTC, mahenning commented
Last two commits added a large part of formatting fixes and nothing much else, maybe it's easier to check by commit.

2024-05-15 18:19 UTC, JSchmie requested changes
Overall good, but there are two major issues. 
The first one, please ensure code coverage, you made a major change without testing it properly.
The second is that you run the classes in a cycle, which is confusing and causes problems.
For that reason, I would suggest making an extra function to get the Whisper Classes.

2024-05-16 07:58 UTC, mahenning commented
> The second is that you run the classes in a cycle, which is confusing and causes problems.

What do you mean by that? What cycle?

2024-05-16 08:29 UTC, JSchmie commented
You use `Transcriber`  as a base class. But later on, you use `Transcriber` to call the inherit classes using a Class method. A class method is designed to init a Class by a function, not to init another class. 
In principle, I am fine with using `Transcriber` to load other classes again but then use a `@staticmethod` instead.

2024-05-16 08:33 UTC, mahenning commented on scraibe/transcriber.py
> +            _model = WhisperTranscriber.load_model(
In your implementation of Transcriber, you used a class method for `load_model`. Why not here? Should WhisperTranscriber/WhisperxTranscriber `load_model` be called directly? How would this confuse users? A base class call can be used for scalability if we would want ot add even more whisper alternatives. (Maybe not the best idea to add half a dozen whisper implementations as deps)

(Not to nitpick too much, but in general a "should do this" is always more helpful to me than a "should not do this". I still have no idea what exactly I should do here.)

2024-05-16 11:04 UTC, mahenning commented on scraibe/autotranscript.py
> -            self.transcriber = Transcriber.load_model(whisper_model, **kwargs)
Yes. I added the return type hint to adress this. Type hint is now
```
-> Union[WhisperTranscriber, WhisperXTranscriber]```

2024-05-16 11:04 UTC, mahenning commented on scraibe/transcriber.py
> +class WhisperXTranscriber(Transcriber):
Done.

2024-05-16 11:05 UTC, mahenning commented on scraibe/transcriber.py
> +class WhisperTranscriber(Transcriber):
Done.

2024-05-16 11:10 UTC, mahenning commented
Changed decorator of `load_model` from `@classmethod` to `@staticmethod`.

2024-05-16 11:11 UTC, mahenning commented on test/test_transcriber.py
Is this right now what you meant? Extended the tests, and test for each subclass. Also added test for wrong input (could be also extended for more wrong input)

2024-05-17 14:28 UTC, merged